# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 7e506c7ade460dc7d1dbda29554cc1658a3ecc676ec8cd480ab83fe84a41a53ec543e7b7e857f30c07c6bda99be75252c1c602cb912e0b1e6f57099982d66a0a

test:
  secret_key_base: fd941afbd72978d11613941f09f9f22639a750db3f5c5dcbbf8e56de4d7bf73ada5d1332d218a344f814956c5828ac7d7d1c9b9ca6ddc6177bf159e4e8a40c7c

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
